---
- name: Deploy Application on Azure VM
  hosts: all
  become: true
  vars:
    frontend_repo: "https://github.com/Team-Sharks-1/Frontend.git"
    backend_repo: "https://github.com/Team-Sharks-1/Backend.git"
    frontend_dir: "/var/www/frontend"
    backend_dir: "/var/www/backend"
    docker_image: "armanlamba/sharks:latest"
    frontend_tag: frontend-v-{{ timestamp.stdout }}
    backend_tag: backend-v-{{ timestamp.stdout }}
    mysql_tag: mysql-v-{{ timestamp.stdout }}

  tasks:
    # Update and install required packages
    - name: Update and install required packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - git
          - docker.io
          - python3-pip
        state: present

    # Install Docker Python module
    - name: Install Docker Python module
      ansible.builtin.pip:
        name: docker
        state: present

    # Start and enable Docker service
    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    # Login to Docker Hub
    - name: Login to Docker Hub
      community.docker.docker_login:
        username: "{{ DOCKER_USERNAME }}"
        password: "{{ DOCKER_PASSWORD }}"

    # Clone Frontend repository
    - name: Clone Frontend repository
      ansible.builtin.git:
        repo: "{{ frontend_repo }}"
        dest: "{{ frontend_dir }}"
        version: main
        force: true

    # Clone Backend repository
    - name: Clone Backend repository
      ansible.builtin.git:
        repo: "{{ backend_repo }}"
        dest: "{{ backend_dir }}"
        version: main
        force: true

    # Replace localhost with public IP in Frontend code (excluding node_modules)
    - name: Replace localhost with public IP in Frontend code
      ansible.builtin.shell: |
        find {{ frontend_dir }} \
          -type f \( -name "*.js" -o -name "*.ts" -o -name "*.json" \) \
          ! -path "*/node_modules/*" \
          -exec sed -i "s/localhost/{{ ansible_host }}/g" {} \; -exec echo "Modified: {}" \;
      register: frontend_replace_output

    - name: Debug Frontend Replacement Output
      ansible.builtin.debug:
        msg: "{{ frontend_replace_output.stdout_lines }}"

    # Replace localhost with public IP in Backend code (excluding node_modules)
    - name: Replace localhost with public IP in Backend code
      ansible.builtin.shell: |
        find {{ backend_dir }} \
          -type f \( -name "*.js" -o -name "*.ts" -o -name "*.json" \) \
          ! -path "*/node_modules/*" \
          -exec sed -i "s/localhost/{{ ansible_host }}/g" {} \; -exec echo "Modified: {}" \;
      register: backend_replace_output

    - name: Debug Backend Replacement Output
      ansible.builtin.debug:
        msg: "{{ backend_replace_output.stdout_lines }}"

    - name: Generate timestamp for unique Docker image tag in EST timezone
      ansible.builtin.shell: |
        set -o pipefail
        date +%Y-%m-%d-%H%M | tr -d '"'
      environment:
        TZ: America/New_York
      register: timestamp
      changed_when: false
      args:
        executable: /bin/bash

    - name: Debug Raw Timestamp
      ansible.builtin.debug:
        var: timestamp.stdout

    - name: Log the generated timestamp
      ansible.builtin.debug:
        msg: "Generated timestamp: {{ timestamp.stdout | regex_replace('\"', '') }}"

    # Build Frontend Docker image
    - name: Build Frontend Docker image
      ansible.builtin.command: sudo docker build -t armanlamba/sharks:{{ frontend_tag }} .
      args:
        chdir: "{{ frontend_dir }}"
      register: frontend_build_output
      changed_when: "'Successfully built' in frontend_build_output.stdout"

    # Push Frontend Docker image
    - name: Push Frontend Docker image
      ansible.builtin.command: sudo docker push armanlamba/sharks:{{ frontend_tag }}
      register: frontend_push_output
      changed_when: "'pushed' in frontend_push_output.stdout"

    # Build Backend Docker image
    - name: Build Backend Docker image
      ansible.builtin.command: sudo docker build -t armanlamba/sharks:{{ backend_tag }} .
      args:
        chdir: "{{ backend_dir }}"
      register: backend_build_output
      changed_when: "'Successfully built' in backend_build_output.stdout"

    # Push Backend Docker image
    - name: Push Backend Docker image
      ansible.builtin.command: sudo docker push armanlamba/sharks:{{ backend_tag }}
      register: backend_push_output
      changed_when: "'pushed' in backend_push_output.stdout"

    # Build MySQL Docker image
    - name: Build MySQL Docker image
      ansible.builtin.command: sudo docker build -t armanlamba/sharks:{{ mysql_tag }} -f {{ backend_dir }}/Dockerfile_mysql .
      args:
        chdir: "{{ backend_dir }}"
      register: mysql_build_output
      changed_when: "'Successfully built' in mysql_build_output.stdout"

    # Push MySQL Docker image
    - name: Push MySQL Docker image
      ansible.builtin.command: sudo docker push armanlamba/sharks:{{ mysql_tag }}
      register: mysql_push_output
      changed_when: "'pushed' in mysql_push_output.stdout"
   
    # Ensure Docker network exists
    - name: Create Docker network
      ansible.builtin.command: |
        docker network inspect my-network || docker network create my-network
      args:
        warn: false

    # Run Frontend container
    - name: Run Frontend container
      ansible.builtin.command: |
        docker run -d --name frontend-container --network my-network -p 3000:3000 armanlamba/sharks:{{ frontend_tag }}
      args:
        warn: false

    # Run MySQL container
    - name: Run MySQL container
      ansible.builtin.command: |
        docker run -d --name mysql-container --network my-network -p 3306:3306 armanlamba/sharks:{{ mysql_tag }}
      args:
        warn: false

    # Run Backend container
    - name: Run Backend container
      ansible.builtin.command: |
        docker run -d --name backend-container --network my-network -p 3001:3001 armanlamba/sharks:{{ backend_tag }}
      args:
        warn: false

    # Verify Running Containers
    - name: List Running Containers
      ansible.builtin.command: docker ps
      register: docker_ps_output

    - name: Debug Running Containers
      ansible.builtin.debug:
        var: docker_ps_output.stdout
