---
- name: Deploy Application on Azure VM
  hosts: all
  become: true
  vars:
    frontend_repo: "https://github.com/Team-Sharks-1/Frontend.git"
    backend_repo: "https://github.com/Team-Sharks-1/Backend.git"
    frontend_dir: "/var/www/frontend"
    backend_dir: "/var/www/backend"
    docker_image: "armanlamba/sharks:latest"
    frontend_tag: frontend-v-{{ timestamp.stdout }}
    backend_tag: backend-v-{{ timestamp.stdout }}
    mysql_tag: mysql-v-{{ timestamp.stdout }}

  tasks:
    - name: Update and install required packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - git
          - docker.io
          - python3-pip
        state: present

    - name: Install Docker Python module
      ansible.builtin.pip:
        name: docker
        state: present

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Login to Docker Hub
      community.docker.docker_login:
        username: "{{ DOCKER_USERNAME }}"
        password: "{{ DOCKER_PASSWORD }}"

    - name: Clone Frontend repository
      ansible.builtin.git:
        repo: "{{ frontend_repo }}"
        dest: "{{ frontend_dir }}"
        version: main
        force: true

    - name: Clone Backend repository
      ansible.builtin.git:
        repo: "{{ backend_repo }}"
        dest: "{{ backend_dir }}"
        version: main
        force: true

    - name: Generate timestamp for unique Docker image tag in EST timezone
      ansible.builtin.command: date +%Y-%m-%d-%H%M
      environment:
        TZ: America/New_York
      register: timestamp
      changed_when: false

    # Build Frontend Docker image
    - name: Build Frontend Docker image
      ansible.builtin.command: sudo docker build -t armanlamba/sharks:{{ frontend_tag }} .
      args:
        chdir: "{{ frontend_dir }}"

    # Push Frontend Docker image
    - name: Push Frontend Docker image
      ansible.builtin.command: sudo docker push armanlamba/sharks:{{ frontend_tag }}

    # Build Backend Docker image
    - name: Build Backend Docker image
      ansible.builtin.command: sudo docker build -t armanlamba/sharks:{{ backend_tag }} .
      args:
        chdir: "{{ backend_dir }}"

    # Push Backend Docker image
    - name: Push Backend Docker image
      ansible.builtin.command: sudo docker push armanlamba/sharks:{{ backend_tag }}

    # Build MySQL Docker image
    - name: Build MySQL Docker image
      ansible.builtin.command: sudo docker build -t armanlamba/sharks:{{ mysql_tag }} -f {{ backend_dir }}/Dockerfile_mysql .
      args:
        chdir: "{{ backend_dir }}"

    # Push MySQL Docker image
    - name: Push MySQL Docker image
      ansible.builtin.command: sudo docker push armanlamba/sharks:{{ mysql_tag }}
