# ansible/deploy.yml

---
- name: Deploy Application on Azure VM
  hosts: all
  become: yes
  vars:
    frontend_repo: "https://github.com/Team-Sharks-1/Frontend.git"
    backend_repo: "https://github.com/Team-Sharks-1/Backend.git"
    frontend_dir: "/var/www/frontend"
    backend_dir: "/var/www/backend"
    docker_image: "armanlamba/sharks:latest"

  tasks:
    - name: Update and install required packages
      apt:
        update_cache: yes
        name:
          - git
          - docker.io
          - python3-pip
        state: present

    - name: Install Docker Python module
      pip:
        name: docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Login to Docker Hub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Clone Frontend repository
      git:
        repo: "{{ frontend_repo }}"
        dest: "{{ frontend_dir }}"
        update: yes

    - name: Clone Backend repository
      git:
        repo: "{{ backend_repo }}"
        dest: "{{ backend_dir }}"
        update: yes

    - name: Build and push Docker image
      shell: |
        cd /var/www
        docker build -t {{ docker_image }} .
        docker push {{ docker_image }}
      args:
        chdir: /var/www

    - name: Pull the latest Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Stop existing container if exists
      docker_container:
        name: sharks_app
        state: absent
        force: yes

    - name: Run Docker container
      docker_container:
        name: sharks_app
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        ports:
          - "80:80"