---
- name: Deploy Application on Azure VM
  hosts: all
  become: true
  vars:
    frontend_repo: "https://github.com/Team-Sharks-1/Frontend.git"
    backend_repo: "https://github.com/Team-Sharks-1/Backend.git"
    frontend_dir: "/var/www/frontend"
    backend_dir: "/var/www/backend"
    docker_image: "armanlamba/sharks:latest"
    frontend_branch: main  # Specify the branch to pin (or use a specific commit hash)
    backend_branch: main

  tasks:
    - name: Update and install required packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - git
          - docker.io
          - python3-pip
        state: present

    - name: Install Docker Python module
      ansible.builtin.pip:
        name: docker
        state: present

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Login to Docker Hub
      community.docker.docker_login:
        username: "{{ DOCKER_USERNAME }}"
        password: "{{ DOCKER_PASSWORD }}"

    # Clone Frontend repository with a pinned branch
    - name: Clone Frontend repository
      ansible.builtin.git:
        repo: "{{ frontend_repo }}"
        dest: "{{ frontend_dir }}"
        version: "{{ frontend_branch }}"  # Ensures consistent results by pinning to 'main' branch
        force: true  # Ensures local changes are overridden

    # Clone Backend repository with a pinned branch
    - name: Clone Backend repository
      ansible.builtin.git:
        repo: "{{ backend_repo }}"
        dest: "{{ backend_dir }}"
        version: "{{ backend_branch }}"  # Ensures consistent results by pinning to 'main' branch
        force: true  # Ensures local changes are overridden

    - name: Generate timestamp for unique Docker image tag in EST timezone
      ansible.builtin.command: date +%Y-%m-%d-%H%M
      environment:
        TZ: America/New_York
      register: timestamp
      changed_when: false

    - name: Build and push Frontend Docker image
      ansible.builtin.command: >
        docker build -t armanlamba/sharks:frontend-v-{{ timestamp.stdout }} . &&
        docker push armanlamba/sharks:frontend-v-{{ timestamp.stdout }}
      args:
        chdir: /var/www/frontend
      changed_when: true

    - name: Build and push Backend Docker image
      ansible.builtin.command: >
        docker build -t armanlamba/sharks:backend-v-{{ timestamp.stdout }} . &&
        docker push armanlamba/sharks:backend-v-{{ timestamp.stdout }}
      args:
        chdir: /var/www/backend
      changed_when: true

    - name: Build and push MySQL Docker image
      ansible.builtin.command: >
        docker build -t armanlamba/sharks:mysql-v-{{ timestamp.stdout }} -f {{ backend_dir }}/Dockerfile_mysql . &&
        docker push armanlamba/sharks:mysql-v-{{ timestamp.stdout }}
      args:
        chdir: /var/www/backend
      changed_when: true
