name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering, e.g., for destroy

jobs:
  build_and_push_docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t armanlamba/sharks:latest .

      - name: Push Docker Image
        run: |
          docker push armanlamba/sharks:latest

  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: build_and_push_docker
    outputs:
      public_ip: ${{ steps.get_ip.outputs.public_ip }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 'latest' # Always uses the latest stable Terraform version

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve tfplan

      - name: Get Public IP
        id: get_ip
        working-directory: infra
        run: echo "public_ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT

  ansible_deploy:
    name: Run Ansible Playbook
    runs-on: ubuntu-latest
    needs: terraform_apply
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Ansible and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible sshpass

      - name: Set Up SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create Ansible Inventory
        run: |
          echo "[web]" > ansible/hosts.ini
          echo "${{ needs.terraform_apply.outputs.public_ip }} ansible_user=azureuser" >> ansible/hosts.ini

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/hosts.ini ansible/deploy.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  terraform_destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 'latest' # Always uses the latest stable Terraform version

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Destroy
        working-directory: infra
        run: terraform destroy -auto-approve
